services:
  # openwebui:
  #   container_name: open-webui
  #   image: ghcr.io/open-webui/open-webui:main
  #   environment:
  #     - WEBUI_AUTH=False
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - open-webui:/app/backend/data
  #   restart: unless-stopped

  rag-api:
    build: ./advanced-rag-offline
    container_name: rag
    volumes:
      - ./advanced-rag-offline/documents:/app/documents
      - ./advanced-rag-offline/cache:/app/cache
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - GENERATOR_MODEL=llama3:8b
      - RERANKER_MODEL=qllama/bge-reranker-large:q4_k_m
      - QUERY_TRANSFORMER_MODEL=llama3:8b
      - TRANSLATOR_MODEL=mistral-nemo:12b
      - EMBEDDING_MODEL=nomic-embed-text
      - DOCS_LANG=ar
    # networks:
    #   - rag-net

volumes:
  open-webui: