services:
  openwebui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - WEBUI_AUTH=False
    ports:
      - "8080:8080"
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
  ddg-scraper-tool:
    build: .
    container_name: ddg_playwright_tool
    environment:
      - Summarizer_HOST=host.docker.internal:11434
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  open-webui: